INSERT INTO `users` (
        `id`,
        `name`,
        `email`,
        `password`,
        `created_at`,
        `updated_at`
    )
VALUES (
        NULL,
        'Test Name',
        'test@test.com',
        '$2a$12$G0QA1yxQL9d2Bn3tpNquAut7s6D8HtuJ8joBSAFK/2Rb0yOeDni8C',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        NULL,
        'test name 2',
        'test2@gmail.com',
        '$2a$12$TJbdIYdGUWakwm7kEQZc7OewQtOqDoiRPhsmQ6x7/1SelQeXZsa7q',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ) -- generated from code
INSERT INTO users (
        `name`,
        `email`,
        `password`,
        `created_at`,
        `updated_at`
    )
VALUES (
        'Helen',
        'Tomasa37@yahoo.com',
        '$2b$10$K0YfkW16UdVrW1wEtf3d9OyMY4IHI1aQfFOAq5jGD0xNyAbZZf0I2',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
(
        'Lurline',
        'Rocky.Huels95@hotmail.com',
        '$2b$10$0AvN5tGdHAok3NaNv/eOPeFh9gM2EpUKKkkLvo5WYcU7RkhdfZ5vC',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
(
        'Tracey',
        'Shakira.Bednar@yahoo.com',
        '$2b$10$JcT/6FRU8AkqkC/vdWsLruNtCpr0kVYCnG1ZiL1Qo/9RzvT/fVVWK',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
(
        'Myles',
        'Alayna_Sauer43@yahoo.com',
        '$2b$10$J9RM/wgnNUB3m0J4IydSeOrBMT1U.L7vEhGVYwPYTmJTDoyCwuXxG',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
(
        'Barney',
        'Madisen8@gmail.com',
        '$2b$10$b7A/pyhdEgNfqWecO1jrLu8aC7qPn3vvv9mOzSHRtS4v3ons8GpaS',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
(
        'Kayden',
        'Raymundo83@yahoo.com',
        '$2b$10$MZQwQTxt9QAY6bYGJRoi0eX.lcr1fN6K8COZKclou1NNkgM6Bxl/O',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
(
        'Jovanny',
        'Ashly.Doyle@gmail.com',
        '$2b$10$QP1kqQRywEdr1Mey66/skumclkGIU/91haamMijiHS/m6wp6Gtnc.',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
(
        'Alexa',
        'Hazel64@yahoo.com',
        '$2b$10$L/lPZdeeRmDQqGCpN1ZJ.e7LMyIhQbbfK8NRRpVe3Y24qkHbvnzru',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
(
        'Ashleigh',
        'Louisa_Olson96@yahoo.com',
        '$2b$10$9UdNyQZMoQ9ENuGg2MXTD.wt5seOFYLe01BE4dhNm3xQreX/XlVMy',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
(
        'Mireya',
        'Thaddeus.Lowe@gmail.com',
        '$2b$10$NfPBLXV9hrlvxct5ZSwb7ulSMb.VXChnZUleclLt4mVfLj3nfw/7i',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    )